const AUTH_USER_ID = '17'
const FIREBASE_API_KEY = 'AIzaSyCtq-vPZPFF81_ewMkrQzjZ4luQweGdkSc'
const FIREBASE_ID = 'poc-chat-fde02'
const FIREBASE_DATABASE_NAME = 'poc-chat-fde02'
const FIREBASE_STORAGE_BUCKET_NAME = 'gs://poc-chat-fde02'

export {
  AUTH_USER_ID,
  FIREBASE_API_KEY,
  FIREBASE_ID,
  FIREBASE_DATABASE_NAME,
  FIREBASE_STORAGE_BUCKET_NAME
}
